<a href="https://colab.research.google.com/github/arnav307/Concept-and-technology-of-AI/blob/main/worksheet_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [6]:
# 4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
# Problem - 1: Array Creation:
# Complete the following Tasks:
# 1. Initialize an empty array with size 2X2.
arr=np.empty((2,2))
print(arr)
# 2. Initialize an all one array with size 4X2.
arr = np.ones((4, 2))
print(arr)
arr = np.full((4, 2), 7)
print(arr)
# 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
a = np.array([[3, 5, 7],[1, 2, 9]])
z = np.zeros_like(a)
print(z)
# 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
a = np.array([[4, 8, 2],[1, 3, 7]])
ones_arr = np.ones_like(a)
print(ones_arr)
# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1, 2, 3, 4]
arr = np.array(new_list)
print(arr)

[[3.51786395e-315 0.00000000e+000]
 [4.94065646e-324 6.63150577e-310]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]
 [7 7]
 [7 7]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[1 2 3 4]


In [7]:
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
# Complete the following tasks:
# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
arr = np.arange(10, 50)
print(arr)
# 2. Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()}
arr = np.arange(9).reshape(3, 3)
print(arr)
# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
identity_matrix = np.eye(3)
print(identity_matrix)
# 4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}
arr = np.random.random(30)
mean_value = arr.mean()
print(arr)
print("Mean:", mean_value)

# 5. Create a 10X10 array with random values and find the minimum and maximum values.
arr = np.random.random((10, 10))
min_val = arr.min()
max_val = arr.max()
print("Array:\n", arr)
print("Minimum value:", min_val)
print("Maximum value:", max_val)
# 6. Create a zero array of size 10 and replace 5th element with 1.
arr = np.zeros(10)
arr[4] = 1
print(arr)
# 7. Reverse an array arr = [1,2,0,0,4,0].
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)
# 8. Create a 2d array with 1 on border and 0 inside.
rows, cols = 5, 5
arr = np.ones((rows, cols))
arr[1:-1, 1:-1] = 0
print(arr)
# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)

# Fill alternating elements with 1
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.25663964 0.43214837 0.15180141 0.56482951 0.60242039 0.1261932
 0.77418931 0.6054426  0.89848594 0.02953654 0.77742685 0.94284714
 0.01893145 0.63534589 0.44345858 0.54818706 0.46302647 0.21595769
 0.49226443 0.86651927 0.93711487 0.03933546 0.46478963 0.86483874
 0.89436185 0.29165228 0.03166647 0.34086743 0.06829961 0.92037014]
Mean: 0.48996494042279515
Array:
 [[0.58281039 0.64741936 0.43755629 0.29308677 0.30132527 0.36640196
  0.0553074  0.65250385 0.50582412 0.34903857]
 [0.352897   0.31597046 0.21959476 0.40158093 0.23346466 0.96609499
  0.0733489  0.97371734 0.55032544 0.01310904]
 [0.92427573 0.42762034 0.63234446 0.9591685  0.79661575 0.37128428
  0.21601969 0.51293083 0.02334346 0.37727344]
 [0.11973707 0.80562256 0.26642608 0.11420969 0.94103299 0.61718492
  0.70129708 0.82956059 0.8355

In [15]:
# For the following arrays:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10]);
w = np.array([11,12]);
# Complete all the task using numpy:
# 1. Add the two array.
add_xy = x + y
print(add_xy)
# 2. Subtract the two array.
sub_xy = x - y
print(sub_xy)
# 3. Multiply the array with any integers of your choice.
mult_x = x * 3
print(mult_x)
# 4. Find the square of each element of the array.
square_x = x**2
print(square_x)

# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_vw = np.dot(v, w)
print(dot_vw)

dot_xv = np.dot(x, v)
print(dot_xv)

dot_xy = np.dot(x, y)
print(dot_xy)


# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.#{Hint:try np.concatenate() or np.vstack() functions.
concat_xy_row = np.concatenate((x, y), axis=0)
concat_xy_row_v = np.vstack((x, y))
print(concat_xy_row)


# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)

concat_vw_col = np.concatenate((v_col, w_col), axis=1)
concat_vw_col_h = np.hstack((v_col, w_col))
print(concat_vw_col)


[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [17]:
# For the following arrays:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);
# Prove following with Numpy:
# 1. Prove A.A−1 = I.
A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A^-1 =\n", identity)

# 2. Prove AB ̸= BA.
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)
print("AB == BA ?", np.array_equal(AB, BA))

# Prove (AB)

# T = BTAT
# .

AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)
print("(AB)^T =\n", AB_T)
print("B^T * A^T =\n", BT_AT)
print("(AB)^T == B^T * A^T ?", np.array_equal(AB_T, BT_AT))



# • Solve the following system of Linear equation using Inverse Methods.

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
# Coefficient matrix A
coeff = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])

B = np.array([-1, -3, 9])
X = np.dot(np.linalg.inv(coeff), B)
print("Solution [x, y, z] =", X)

# • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
# of Numpy}
X_solve = np.linalg.solve(coeff, B)
print("Solution using np.linalg.solve:", X_solve)



A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB == BA ? False
(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
(AB)^T == B^T * A^T ? True
Solution [x, y, z] = [ 2.  1. -2.]
Solution using np.linalg.solve: [ 2.  1. -2.]


In [ ]:
# 4.2 Experiment: How Fast is Numpy?
# In this exercise, you will compare the performance and implementation of operations using plain Python
# lists (arrays) and NumPy arrays. Follow the instructions:
# 1. Element-wise Addition:
# • Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
# and Print the time taken for this operation.
# • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
# operation.
import time
size = 1_000_000


list1 = list(range(size))
list2 = list(range(size))

start = time.time()
list_add = [a + b for a, b in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start, "seconds")


arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy array addition time:", end - start, "seconds")

# 2. Element-wise Multiplication
# • Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
# sure and Print the time taken for this operation.

# • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
# operation.
start = time.time()
list_mul = [a * b for a, b in zip(list1, list2)]
end = time.time()
print("Python list multiplication time:", end - start, "seconds")


start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy array multiplication time:", end - start, "seconds")

# 3. Dot Product
# • Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
# Print the time taken for this operation.
# • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
# operation.
start = time.time()
dot_list = sum(a * b for a, b in zip(list1, list2))
end = time.time()
print("Python list dot product time:", end - start, "seconds")


start = time.time()
dot_array = np.dot(arr1, arr2)
end = time.time()
print("NumPy array dot product time:", end - start, "seconds")

# 4. Matrix Multiplication
# • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
# and print the time taken for this operation.

# • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
# sure and print the time taken for this operation.
matrix_size = 1000


mat1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
mat2 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]

start = time.time()

result = [[sum(mat1[i][k] * mat2[k][j] for k in range(matrix_size))
           for j in range(matrix_size)] for i in range(matrix_size)]
end = time.time()
print("Python list matrix multiplication time:", end - start, "seconds")


np_mat1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
np_mat2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

start = time.time()
np_result = np.dot(np_mat1, np_mat2)
end = time.time()
print("NumPy array matrix multiplication time:", end - start, "seconds")

Python list addition time: 0.06009960174560547 seconds
NumPy array addition time: 0.00405430793762207 seconds
Python list multiplication time: 0.06431722640991211 seconds
NumPy array multiplication time: 0.004029273986816406 seconds
Python list dot product time: 0.09485197067260742 seconds
NumPy array dot product time: 0.0015921592712402344 seconds
